GET http://localhost:8080/greet

###
GET http://localhost:8080/
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXRlIjoiMjAyMy0wMS0wM1QwOTo1NTo1Ny41ODEzMDk1MDAiLCJzdWIiOiJ1c2VyMyIsInJvbGUiOiJ1c2VyIiwibWVzc2FnZSI6InNvbWUgb3RoZXIgbWVzc2FnZSIsImV4cCI6MTY3MjcyMzU1NywiaWF0IjoxNjcyNzE5OTU3fQ.M4uIHYwL5pvNgNf1Mc4-OkF0rVMVU07Ne7hduaJyBhmfscMHi97a3TGBB2R0gXKWiX4my4lEkylFM02JMQBhtA

###
GET http://localhost:8080/demo/item/block
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXRlIjoiMjAyMy0wMS0wOVQwOToxNjo0Ni43NDgxNzAxMDAiLCJzdWIiOiJ1c2VyMSIsInJvbGUiOiJ1c2VyIiwibWVzc2FnZSI6InNvbWUgb3RoZXIgbWVzc2FnZSIsImV4cCI6MTY3MzIzOTYwNiwiaWF0IjoxNjczMjM2MDA2fQ.dphRl5Y9f4iSUqSauioxZfP1oxESkECAN1IGnnDRHSJ4xNnSlt1Yclok2GPv5dr_drSRntazWQJL0OlWnQRxqQ

###
GET http://localhost:8080/demo/item/create
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXRlIjoiMjAyMy0wMS0wOVQwOToxNzoyMS4zMjQxOTc0MDAiLCJzdWIiOiJ1c2VyMyIsInJvbGUiOiJ1c2VyIiwibWVzc2FnZSI6InNvbWUgb3RoZXIgbWVzc2FnZSIsImV4cCI6MTY3MzIzOTY0MSwiaWF0IjoxNjczMjM2MDQxfQ.4YYssXmlotp26qEXTzClRLypqvJUVjgBKH-NQdKd1avwQl494QteaWVjmdpQWWR1vr3rKt8S67BKMCffDNbC_g

###

POST http://localhost:8080/authenticate
content-type: application/json

{
    "username": "user1",
    "password": "demo@123"
}
###

POST http://localhost:8080/authenticate
content-type: application/json

{
    "username": "user2",
    "password": "demo@123"
}
###

POST http://localhost:8080/authenticate
content-type: application/json

{
    "username": "user3",
    "password": "demo@123"
}


###
# admin
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXRlIjoiMjAyMy0wMS0wOVQwOToxNjo0Ni43NDgxNzAxMDAiLCJzdWIiOiJ1c2VyMSIsInJvbGUiOiJ1c2VyIiwibWVzc2FnZSI6InNvbWUgb3RoZXIgbWVzc2FnZSIsImV4cCI6MTY3MzIzOTYwNiwiaWF0IjoxNjczMjM2MDA2fQ.dphRl5Y9f4iSUqSauioxZfP1oxESkECAN1IGnnDRHSJ4xNnSlt1Yclok2GPv5dr_drSRntazWQJL0OlWnQRxqQ

# seller
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXRlIjoiMjAyMy0wMS0wOVQwOToxNzoxMS4xNDIyMjEzMDAiLCJzdWIiOiJ1c2VyMiIsInJvbGUiOiJ1c2VyIiwibWVzc2FnZSI6InNvbWUgb3RoZXIgbWVzc2FnZSIsImV4cCI6MTY3MzIzOTYzMSwiaWF0IjoxNjczMjM2MDMxfQ.ioRpuMlT1D4fXCeZnDzeoKzChhwRl0Kfr3qAdLP38z_nbA4yaBmwJasuyIQ7JzJ3banJ6A4E4q3HFPELhJ20AA

# buyer
# Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJkYXRlIjoiMjAyMy0wMS0wOVQwOToxNzoyMS4zMjQxOTc0MDAiLCJzdWIiOiJ1c2VyMyIsInJvbGUiOiJ1c2VyIiwibWVzc2FnZSI6InNvbWUgb3RoZXIgbWVzc2FnZSIsImV4cCI6MTY3MzIzOTY0MSwiaWF0IjoxNjczMjM2MDQxfQ.4YYssXmlotp26qEXTzClRLypqvJUVjgBKH-NQdKd1avwQl494QteaWVjmdpQWWR1vr3rKt8S67BKMCffDNbC_g
